title: Micro, Yet Mighty
description: My semi-professional blog

url: http://perrykai.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: perrykai
   twitter: KDaza16
   facebook: kaitlyn.perry.12
   email: perrykai@msu.edu

google_analytics: "UA-58263416-1"
